When running with no display, do not fail.
Setting the environment variable ETS_TOOLKIT='null' causes Traits UI
to mostly be a no-op. However, I was getting this exception:

    File "/home/strawlab/src/motmot/fview_ext_trig/motmot/fview_ext_trig/live_timestamp_modeler.py", line 22, in <module>
      from chaco.chaco_plot_editor import ChacoPlotItem
    File "/usr/lib/python2.7/dist-packages/chaco/chaco_plot_editor.py", line 52, in <module>
      color_editor = RGBAColorEditor()
    TypeError: 'NoneType' object is not callable

This is a workaround.